// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIGgj1SOn3aP5jdE4OeRGtebYkWBp8mp4',
    appId: '1:466370124600:web:76b69c68602ef7100f7fcd',
    messagingSenderId: '466370124600',
    projectId: 'shopapp-14acd',
    authDomain: 'shopapp-14acd.firebaseapp.com',
    storageBucket: 'shopapp-14acd.appspot.com',
    measurementId: 'G-H93EXX6CVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr-VLXnvZaSZdcZeBwnMRsD5g0dMtZouU',
    appId: '1:466370124600:android:5c7c207625a6bdd00f7fcd',
    messagingSenderId: '466370124600',
    projectId: 'shopapp-14acd',
    storageBucket: 'shopapp-14acd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI6YUBKXNpCplAC7QJU_---yhah9O8WbI',
    appId: '1:466370124600:ios:d648482d5e8d8b480f7fcd',
    messagingSenderId: '466370124600',
    projectId: 'shopapp-14acd',
    storageBucket: 'shopapp-14acd.appspot.com',
    iosClientId: '466370124600-jd539qainhftiteh0nguo0hqmmro8kqp.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopp',
  );
}
